### ISSUE TITLE
100% height on several elements breaking scroll on firefox

### ISSUE THREAD

**Issue by Spreeuw** [myparcelnl/checkout#1]
`#mypa-slider`, `.mypa-tab-container` & `#mypa-delivery-options-container` have a 100% height set in the styles.
https://github.com/myparcelnl/checkout/blob/master/index.html#L25
https://github.com/myparcelnl/checkout/blob/master/index.html#L40
https://github.com/myparcelnl/checkout/blob/master/index.html#L40

In firefox, this breaks scrolling when the content becomes larger than the iframe itself. In addition, when working with a flexible height of the iframe, the height of the contents does not change when requested via JS/jQuery. Removing the height fixes both of these issues.

**Comment by SimonCsoma** [comment]
This is not directly the solution because this will break the scrolling in chrome. But it is a bug non the less

**Comment by Spreeuw** [comment]
Making the elements themselves that need scrolling scrollable works in Chrome too though, see the solution for Magento that Reindert used: [overflow: scroll](https://github.com/myparcelnl/magento1/blob/8729e546c28e3c1daf0e0d2a5907bb68ad7819f6/app/design/frontend/base/default/template/TIG/MyParcel2014/checkout/mypa_checkout_options.phtml#L357-L360)

**Comment by SimonCsoma** [comment]
It creates 2 scollbars

**Comment by Spreeuw** [comment]
Not if the iframe has a flexible height and scrollbar disabled. (which is preferable in the context of an actual checkout). Having a scrollbar in the first place is not preferable because it breaks the scrolling flow on the main checkout page (especially on mobile devices), so only showing scrollbars on long content is a good alternative here. In Firefox, I always see a scrollbar on the example regardless of the content height:
![schermafbeelding 2016-11-11 om 14 34 23](https://cloud.githubusercontent.com/assets/3217773/20216636/f97dad5c-a81b-11e6-95a9-8264a6a3a76f.png)

**Comment by SimonCsoma** [comment]
Then it would still break the normal use case

**Comment by Spreeuw** [comment]
What's the normal use case? As far as I can see, currently the iframe is the only solution that reliably works cross-browser

**Comment by RichardPerdaan** [comment]
Has been resolved with checkout v2.0.0
