### ISSUE TITLE
"Niet bij de buren" bezorgen blijf op ja staan

### ISSUE THREAD

**Issue by reindert-vetter** [myparcelnl/checkout#11]
@grandcruwijnen.nl: 
We zien wel een bug namelijk als je van de voorgestelde tijdsvenster wisselt naar een later tijdstip en dan weer terugzet dan blijft “Niet bij de buren bezorgen” op Ja staan

**Comment by RichardPerdaan** [comment]
@Sterk.Amsterdam

**Comment by RichardPerdaan** [comment]
Is opgelost met checkout-v2.0.0
