### ISSUE TITLE
Fixed tab width cuts off month for larger font sizes

### ISSUE THREAD

**Issue by Spreeuw** [myparcelnl/checkout#2]
`.mypa-tab` has a fixed width:
https://github.com/myparcelnl/checkout/blob/master/index.html#L75

When using larger font sizes (conforming to the context of the checkout), the month is cut of. Removing the fixed width or setting it to `min-width` fixes this.

**Comment by SimonCsoma** [comment]
You can change the max element width in the html [here](https://github.com/myparcelnl/checkout/blob/master/index.html#L75) manually

**Comment by Spreeuw** [comment]
This is not a question but an issue + suggestion for improvement :)
I linked to that exact line in my first post above

**Comment by RichardPerdaan** [comment]
Has been resolved with checkout v2.0.0
