### ISSUE TITLE
CSS Checkout

### ISSUE THREAD

**Issue by maritbekhuis** [myparcelnl/checkout#25]
Mail van de klant:

" 
Goedemorgen,

Graag wil ik melding maken van een CSS verbetering voor de plugin. Is het mogelijk dit door te geven aan de IT / pluginmaker.

We krijgen met de nieuwe versie van de plugin verschillende resultaten op de afrekenpagina. In Google Chrome Mac bijvoorbeeld komt er een scrollbalk te staan. In Safari voor Mac niet. Zie bijlage. In de code kan ik het niet eenvoudig aanpassen.

In de Javascript file wcmp-frontend.js staat wel scrolling=”auto”, volgens ons is dit een deprecated functie in HTML5 en kan wellicht beter met CSS opgelost worden beter compatible / future-proof te zijn met verschillende browsers. ( https://www.w3schools.com/TAGs/att_iframe_scrolling.asp )

Is het ook mogelijk meteen 15pixels marge onder het iframe toe te voegen? Zo staat de iframe wat netter in de afrekenpagina. We hebben dit nu even zelf met custom css opgelost.

    iframe#myparcel-iframe{
margin-bottom: 15px;
}
"

**Comment by RichardPerdaan** [comment]
Is opgelost met checkout-v2.0.0
