### ISSUE TITLE
Gratis in plaats van 0,00 euro

### ISSUE THREAD

**Issue by reindert-vetter** [myparcelnl/checkout#27]
Een conversie optimalisatie puntje:
![image](https://user-images.githubusercontent.com/16726304/32274774-c8b9af18-bf08-11e7-9f2d-1ec247910dd6.png)
 
Hier staat duidelijk €0,00 (gratis = beter ????)
 
Maar hier:
![image](https://user-images.githubusercontent.com/16726304/32274782-cf170ee6-bf08-11e7-94f4-6834178f900f.png)
Hier staat namelijk niets !!

Lijkt nu misschien voor sommige mensen € 10,00 ??

**Comment by reindert-vetter** [comment]
@vanbeeklederwaren.nl

**Comment by RichardPerdaan** [comment]
Is opgelost met checkout-v2
