### ISSUE TITLE
defaults to retailexpress

### ISSUE THREAD

**Issue by Spreeuw** [myparcelnl/checkout#3]
When the same pickup point is given for both early and normal pickup, the script always returns price_comment: retailexpress. Testing with following postal code + number: 1171CV, 150

**Comment by RichardPerdaan** [comment]
@00210251

**Comment by reindert-vetter** [comment]
@unlimited health

**Comment by RichardPerdaan** [comment]
@330669

**Comment by RichardPerdaan** [comment]
Has been resolved with checkout v2.0.0
