### ISSUE TITLE
last mypa-price cut off

### ISSUE THREAD

**Issue by Spreeuw** [myparcelnl/checkout#4]
When the delivery options are relatively narrow, the bottom last mypa-price element is cut off.
![schermafbeelding 2016-11-29 om 13 38 32](https://cloud.githubusercontent.com/assets/3217773/20710099/28cb0b92-b639-11e6-95fd-292f528ef7aa.png)

This can be fixed by giving it a margin-bottom equal to the wrapping `<label>` element, 10px.
`
.mypa-price { margin-bottom: 10px; }
`

**Comment by RichardPerdaan** [comment]
Has been resolved with checkout v2.0.0
