### ISSUE TITLE
Internationalization of strings & dates

### ISSUE THREAD

**Issue by Spreeuw** [myparcelnl/checkout#6]
To enable internationalization of the checkout script, all hardcoded strings should ideally be moved (or read from) to the settings object.

Some examples:
https://github.com/myparcelnl/checkout/blob/master/js/myparcel.coffee#L109
https://github.com/myparcelnl/checkout/blob/master/js/myparcel.coffee#L113
https://github.com/myparcelnl/checkout/blob/master/js/myparcel.coffee#L334
https://github.com/myparcelnl/checkout/blob/master/js/myparcel.coffee#L449

You get the idea :)

Furthermore, there should be a variable in the settings object to set the locale for Moment. Currently this is done via the constant `NATIONAL`, but this is also used in the AJAX request for the delivery options. These should be separate.

**Note:** This does not cover API responses, which should also be internationalized. Perhaps this can be taken up with the backend developers? For this purpose, the same 'locale' setting that is used for Moment can be passed to the API

**Comment by reindert-vetter** [comment]
@192894 Translate the checkout into English

**Comment by RichardPerdaan** [comment]
Is opgelost met checkout-v2.0.0
