### ISSUE TITLE
iPhone/iPad canvas issue

### ISSUE THREAD

**Issue by Spreeuw** [myparcelnl/checkout#7]
This issue seems to affect all iframe implementations (at least Magento & WooCommerce), although not within all (CSS) contexts.

![myparcel-iframe-ios](https://cloud.githubusercontent.com/assets/3217773/23941211/44dc38f6-0968-11e7-990b-d9fb1d37fa27.png)

I found this: http://stackoverflow.com/questions/23083462/how-to-get-an-iframe-to-be-responsive-in-ios-safari

But that doesn't seem to fix it (neither for me or for @reindert-vetter )

**Comment by Chris707** [comment]
@autovoorkinderen.nl/gereedschapdeal.com

**Comment by reindert-vetter** [comment]
@historischekaart.nl

**Comment by reindert-vetter** [comment]
@gereedschapdeal.com

**Comment by reindert-vetter** [comment]
@keepable.nl /  @rgsport.nl

**Comment by reindert-vetter** [comment]
@rgsport.nl

**Comment by reindert-vetter** [comment]
Possible fix:
https://github.com/myparcelnl/checkout/blob/master/docs/js/myparcel.js#L237
```
$("#mypa-tabs-container").attr('style', "width:" + ($("#mypa-tabs-container").width()) + "px");
$("#mypa-tabs").attr('style', "width:" + (this.deliveryDays.length * 105) + "px");
this.makeSlider();
```

**Comment by RichardPerdaan** [comment]
@www.navigatie-huren.nl

**Comment by RichardPerdaan** [comment]
@Sterk.Amsterdam

**Comment by reindert-vetter** [comment]
@Unlimited Health

**Comment by reindert-vetter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [iPhone/iPad canvas issue](https://trello.com/c/EqUUHEf6/38-iphone-ipad-canvas-issue)

**Comment by RichardPerdaan** [comment]
Is opgelost met checkout-v2.0.0
